### PR TITLE
smart group support

### PR DESCRIPTION
**Pull request by johanv**
This seems to work. I included a small example.

```
  "women": {
    "name":"women",
    "title":"Women",
    "is_active":1,
    "is_reserved":0,
    "group_type":"2",
    "description": "Smart group with all women",
    "form_values": {
        "gender_id":"1"
    }
```

I noticed that if you configure a smart group using the UI, saves the form_values differently. But this works as well, apparently. I use the keys and values of the advanced search form, and I think the CiviCRM UI used to do it like this as well. But maybe this changed in CiviCRM 4.7 (or even 4.6).

Note: creating smart groups like this only works in CiviCRM 4.7 (or later), because the SavedSearch API is not present in CiviCRM 4.6.

### CODE REVIEW

**Comment by johanv** [comment]
This probably needs some more examples. This is a smart group for contacts with relationship type 13, and custom_13 (radio button) is one of 'K' and 'A':

```
   "ketis_aspis": {
       "name": "ketis_aspis",
       "title": "Keti's en aspi's",
       "is_active": 1,
       "is_reserved": 0,
       "description": "Alle actieve keti's en aspi's",
       "parent": "vlam",
       "form_values": {
           "relation_type_id": "13_a_b",
           "custom_13": {
               "IN": {"0":"K", "1":"A"}
           },
           "relation_status": 0
       }
   }
```

relation_status = 0 in advanced search, means that the relationship is active.

**Comment by johanv** [comment]
And another example: if you want to match any of the options of a multiselect value, you need to explicitely specify a or operator:

```
   "leiding_ketis_aspis": {
       "name": "leiding_ketis_aspis",
       "title": "Ketileiding en aspileiding",
       "is_active": 1,
       "is_reserved": 0,
       "description": "Alle actieve keti- en aspileiding",
       "parent": "vlam",
       "form_values": {
           "relation_type_id": "13_a_b",
           "custom_13": {
               "IN": {"0":"L"}
           },
           "custom_14": {
               "IN": {"0":"K", "1":"A"}
           },
           "custom_14_operator": "or",
           "relation_status": 0
       }
   }
```

custom_13 is not multiselect, custom_14 is.

**Comment by jaapjansma** [comment]
@johanv this PR seems to be conflicting. Could you check the conflicts?

**Comment by johanv** [comment]
I merged master back into this PR. The problem was caused by white space issues.

**Pull request merged**
